# This is a basic workflow to help you get started with Actions

name: Issue To Task Action

# Controls when the workflow will run
on:
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created]
    
  workflow_dispatch:

jobs:
  issue-to-task:
    runs-on: ubuntu-latest

    steps:
      - name: Our Action
        uses: ideasonpurpose/github-issues-asana-tasks-action@v0.0.23
        env:
          ASANA_PAT: ${{ secrets.ASANA_TOKEN }}
          TOKEN: ${{ secrets.ASANA_TOKEN }}
